### ISSUE TITLE
Create a Detailed Plan for your application

### ISSUE THREAD

**Issue by DonaldHesler** [kshep425/ALUM-APP#5]
The team needs to come up with a detailed plan of the application that includes the following:

- [x] An overview of the application including why its valuable. (Issue #6  )
- [x] Screen by Screen Layouts (Issue #7 & #Issue #8   )
- [x] Breakdown of the roles of the groups (Issue #9 )
- [x] Schedule of tasks (Issue #9 )
- [x] A Project board and issues for these task
